server:
  port: 8081
  servlet:
    context-path: /rocketmq-notify-pay

spring:
  application:
    name: rocketmq-notify-pay
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3306/db_distributed_transaction_rocketmq_notify_pay?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root

rocketmq:
  producer:
    group: rocketmq_notify_pay
  name-server: 127.0.0.1:9876